import { CreateCarRequest } from './models/models';

const carModels = ['Alfa Romeo Spider',
  'Audi 80 and 90',
  'Audi Coupé',
  'Audi A3',
  'Audi A4',
  'Audi A2',
  'Austin Metro',
  'BMW i3',
  'BMW i8',
  'BMW 3 Series',
  'BMW 5 Series',
  'BMW 8 Series',
  'BMW X5',
  'Buick Electra',
  'Buick Invicta',
  'Buick LeSabre',
  'Buick Riviera',
  'Buick Special',
  'Buick Wildcat',
  'BYD e6',
  'BYD F3DM',
  'BYD Qin',
  'BYD Tang',
  'Cadillac De Ville',
  'Chevrolet Camaro',
  'Chevrolet Caprice',
  'Chevrolet Cavalier',
  'Chevrolet Corvair',
  'Chevrolet Corvette',
  'Chevrolet Cruze',
  'Chevrolet Impala',
  'Chevrolet Malibu',
  'Chevrolet Opala',
  'Chevrolet Suburban',
  'Chevrolet Volt',
  'Chrysler Newport',
  'Chrysler minivans',
  'Chrysler Town & Country',
  'Citroën DS',
  'De Tomaso Pantera',
  'DeSoto Custom',
  'Dodge Coronet',
  'Dodge Viper',
  'Eagle Talon',
  'Edsel Ranger',
  'Edsel Villager',
  'Ferrari 166 MM',
  'Ferrari 250 GTO',
  'Ferrari Dino',
  'Ferrari Testarossa',
  'Fiat Panda',
  'Fiat Punto',
  'Ford Aerostar',
  'Ford Cortina',
  'Ford Crown Victoria',
  'Ford E-Series',
  'Ford Escort',
  'Ford Explorer',
  'Ford F-Series',
  'Ford Falcon',
  'Ford Fiesta',
  'Ford Focus',
  'Ford LTD',
  'Ford Mustang',
  'Ford Puma',
  'Ford Ranchero',
  'Ford Ranger',
  'Ford Ranger (T6)',
  'Ford Sierra',
  'Ford Taurus',
  'Ford Tempo',
  'Ford Thunderbird',
  'Ford Transit',
  'Holden Commodore',
  'Honda Accord',
  'Honda Civic',
  'Honda CR-V',
  'Honda Prelude',
  'Hudson Super',
  'Hyundai Elantra',
  'Hyundai Accent',
  'Hyundai Sonata',
  'Imperial Crown',
  'Jaguar XJ',
  'Jaguar XJS',
  'Jaguar XK',
  'Jeep Cherokee (XJ)',
  'Jeep CJ',
  'Jeep Wrangler',
  'Jeep Cherokee (KL)',
  'Jeep Renegade',
  'Jeep Compass',
  'Kaiser Deluxe',
  'Land Rover Series',
  'Defender',
  'Land Rover Range Rover',
  'Lincoln Continental',
  'Lincoln Town Car',
  'Lola T70',
  'Lotus Elise',
  'Mazda Familia',
  'Mazda MPV',
  'Mazda MX-5',
  'Mazda RX-7',
  'Mazda RX-8',
  'Mercedes-Benz 600',
  'Mercedes-Benz C-Class',
  'Mercedes-Benz G-Class',
  'Mercedes-Benz S-Class',
  'Mercedes-AMG GT',
  'Mercury Bobcat',
  'Mercury Colony Park',
  'Mercury Cougar',
  'Mercury Cyclone',
  'Mercury Grand Marquis',
  'Mercury Marauder',
  'Mercury Mariner',
  'Mercury Milan',
  'Mercury Montego',
  'Mercury Monterey',
  'Mercury Monterey (minivan)',
  'Mercury Mountaineer',
  'Mercury Sable',
  'Mercury Turnpike Cruiser',
  'Mercury Villager',
  'MG F and TF',
  'Mitsubishi Galant',
  'Mitsubishi GTO',
  'Mitsubishi Lancer',
  'Mitsubishi L200',
  'Mitsubishi Outlander P-HEV',
  'Mitsubishi Pajero',
  'Nash Statesman',
  'Nissan Leaf',
  'Nissan Maxima',
  'Nissan Micra',
  'Nissan Qashqai/Rogue Sport',
  'Nissan Tiida',
  'Nissan Sunny',
  'Sentra',
  'Pulsar',
  'Almera',
  'Nissan Z-cars',
  'Oldsmobile Aurora',
  'Oldsmobile Cutlass',
  'Opel Ascona',
  'Opel Astra',
  'Opel Corsa',
  'Opel Vectra',
  'Packard Eight',
  'Plymouth Fury',
  'Plymouth Voyager',
  'Pontiac Bonneville',
  'Pontiac Firebird',
  'Pontiac Grand Am',
  'Porsche 550',
  'Porsche 911',
  'Porsche 908',
  'Porsche 968',
  'Porsche Boxster',
  'Porsche Cayenne',
  'Porsche Panamera',
  'Rambler Classic',
  'Renault Clio',
  'Renault Twingo',
  'Renault Twizy',
  'Renault Zoe',
  'Saturn S-Series',
  'SEAT Ibiza',
  'Škoda Octavia',
  'Studebaker Champion',
  'Subaru Alcyone',
  'Subaru Legacy',
  'Suzuki Wagon R',
  'Toyota Camry',
  'Toyota Celica',
  'Toyota Corolla',
  'Toyota Hilux',
  'Toyota Ipsum',
  'Toyota Land Cruiser',
  'Toyota Mirai',
  'Toyota Prius',
  'Toyota RAV4',
  'Toyota Soarer',
  'Lexus SC',
  'Toyota Stout',
  'Toyota Supra',
  'Vauxhall Viva',
  'Volkswagen Gol',
  'Volkswagen Golf',
  'Volkswagen Jetta',
  'Volkswagen Passat'];

export function getRandomCar(): CreateCarRequest {
  return {
    name: randomModel(),
    color: randomColor(),
  };
}

export function randomModel() {
  return carModels[Math.floor(Math.random() * carModels.length)];
}

function randomColor() {
  return `#${Math.floor(Math.random() * 16777215).toString(16)}`;
}
